apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: maxprime
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/maxprime:latest
          env:
            - name: RELEASE
              value: "v0.0.1-manual"
