apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: maxprime
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/maxprime:latest
            env:
              - name: RELEASE
                value: "v0.0.4-manual"
              - name: GIN_MODE
                value: "release"
